In [69]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [20]:
df=pd.read_csv("./zameen.csv")

In [25]:
df

,url,title,type,price,area,city,address,bedrooms,baths,area_sqft,price_per_sqft,area_sqm,price_per_sqm,Latitude,Longitude,date_added
0,https://www.zameen.com/Property/bahria_town_ba...,5 MARLA BRAND NEW PARK FACING HOUSE FOR SALE,House,23500000.0,5 Marla,Islamabad,"Bahria Town, Islamabad, Islamabad Capital",4 Beds,4 Baths,1361.25,17263.544536,126.464209,185823.326871,33.6844,73.0479,2024-05-25
1,https://www.zameen.com/Property/islamabad_f-7_...,Prime Location House For Sale,House,750000000.0,3.8 Kanal,Islamabad,"F-7, Islamabad, Islamabad Capital",10 Beds,0 Baths,20691.00,36247.643903,1922.255973,390166.559779,33.6844,73.0479,2024-05-25
2,https://www.zameen.com/Property/islamabad_f-7_...,Luxurious 6-Bedroom House For Sale In Prime Lo...,House,450000000.0,2 Kanal,Islamabad,"F-7, Islamabad, Islamabad Capital",6 Beds,6 Baths,10890.00,41322.314050,1011.713670,444789.878148,33.6844,73.0479,2024-05-25
3,https://www.zameen.com/Property/islamabad_f-7_...,Specious 666 Sq Yard 60x100 House For Sale In ...,House,290000000.0,1.3 Kanal,Islamabad,"F-7, Islamabad, Islamabad Capital",6 Beds,6 Baths,7078.50,40969.131878,657.613886,440988.255258,33.6844,73.0479,2024-05-25
4,https://www.zameen.com/Property/islamabad_f-8_...,Prime Location House For Sale,House,225000000.0,1 Kanal,Islamabad,"F-8, Islamabad, Islamabad Capital",5 Beds,5 Baths,5445.00,41322.314050,505.856835,444789.878148,33.6844,73.0479,2024-05-25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155056,https://www.zameen.com/Property/lahore_road_sh...,5 Marla Residential Plot Is Available For Sale...,Residential Plot,2500000.0,5 Marla,Sargodha,"Lahore Road, Sargodha, Punjab",0 Beds,0 Baths,1361.25,1836.547291,126.464209,19768.439029,32.0836,72.6711,2024-05-26
155057,https://www.zameen.com/Property/sargodha_chak_...,Beautiful Laser Leveled Land Available With Hu...,Agricultural Land,15000000.0,50 Kanal,Sargodha,"Chak 74 NB, Sargodha, Punjab",0 Beds,0 Baths,272250.00,55.096419,25292.841750,593.053171,32.0836,72.6711,2024-05-26
155058,https://www.zameen.com/Property/sargodha_khush...,Agriculture Land Sale Urgent,Agricultural Land,24000000.0,48 Kanal,Sargodha,"Khushab Road, Sargodha, Punjab",0 Beds,0 Baths,261360.00,91.827365,24281.128080,988.421951,32.0836,72.6711,2024-05-26
155059,https://www.zameen.com/Property/sargodha_khush...,Agriculture Land Sale Urgent 110 Ft Front On Road,Agricultural Land,33000000.0,103 Kanal,Sargodha,"Khushab Road, Sargodha, Punjab",0 Beds,0 Baths,560835.00,58.840836,52103.254005,633.357755,32.0836,72.6711,2024-05-26
155060,https://www.zameen.com/Property/sargodha_khush...,Agriculture Land Sale Urgent Chak 74 Nb,Agricultural Land,35000000.0,83 Kanal,Sargodha,"Khushab Road, Sargodha, Punjab",0 Beds,0 Baths,451935.00,77.444765,41986.117305,833.608875,32.0836,72.6711,2024-05-26

In [33]:
isb_houses=df[(df["city"]=="Islamabad")&(df["type"]=="House")].copy()

In [27]:
isb_houses

,url,title,type,price,area,city,address,bedrooms,baths,area_sqft,price_per_sqft,area_sqm,price_per_sqm,Latitude,Longitude,date_added
0,https://www.zameen.com/Property/bahria_town_ba...,5 MARLA BRAND NEW PARK FACING HOUSE FOR SALE,House,23500000.0,5 Marla,Islamabad,"Bahria Town, Islamabad, Islamabad Capital",4 Beds,4 Baths,1361.25,17263.544536,126.464209,185823.326871,33.6844,73.0479,2024-05-25
1,https://www.zameen.com/Property/islamabad_f-7_...,Prime Location House For Sale,House,750000000.0,3.8 Kanal,Islamabad,"F-7, Islamabad, Islamabad Capital",10 Beds,0 Baths,20691.00,36247.643903,1922.255973,390166.559779,33.6844,73.0479,2024-05-25
2,https://www.zameen.com/Property/islamabad_f-7_...,Luxurious 6-Bedroom House For Sale In Prime Lo...,House,450000000.0,2 Kanal,Islamabad,"F-7, Islamabad, Islamabad Capital",6 Beds,6 Baths,10890.00,41322.314050,1011.713670,444789.878148,33.6844,73.0479,2024-05-25
3,https://www.zameen.com/Property/islamabad_f-7_...,Specious 666 Sq Yard 60x100 House For Sale In ...,House,290000000.0,1.3 Kanal,Islamabad,"F-7, Islamabad, Islamabad Capital",6 Beds,6 Baths,7078.50,40969.131878,657.613886,440988.255258,33.6844,73.0479,2024-05-25
4,https://www.zameen.com/Property/islamabad_f-8_...,Prime Location House For Sale,House,225000000.0,1 Kanal,Islamabad,"F-8, Islamabad, Islamabad Capital",5 Beds,5 Baths,5445.00,41322.314050,505.856835,444789.878148,33.6844,73.0479,2024-05-25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12250,https://www.zameen.com/Property/kashmir_highwa...,House For Grabs In 8 Kanal Islamabad,House,599100000.0,8 Kanal,Islamabad,"Kashmir Highway, Islamabad, Islamabad Capital",0 Beds,0 Baths,43560.00,13753.443526,4046.854680,148040.897777,33.6844,73.0479,2024-05-26
12251,https://www.zameen.com/Property/kashmir_highwa...,"A House Of 10 Marla In Rs. 53,000,000",House,53000000.0,10 Marla,Islamabad,"Kashmir Highway, Islamabad, Islamabad Capital",0 Beds,0 Baths,2722.50,19467.401286,252.928417,209545.453705,33.6844,73.0479,2024-05-26
12252,https://www.zameen.com/Property/g_11_g-11_2_br...,Brand New House For Sale,House,55000000.0,5 Marla,Islamabad,"G-11, Islamabad, Islamabad Capital",5 Beds,5 Baths,1361.25,40404.040404,126.464209,434905.658634,33.6844,73.0479,2024-05-26
12253,https://www.zameen.com/Property/i_10_i-10_1_be...,Beautiful House At Islamabad Best Location,House,40000000.0,5 Marla,Islamabad,"I-10, Islamabad, Islamabad Capital",4 Beds,4 Baths,1361.25,29384.756657,126.464209,316295.024461,33.6844,73.0479,2024-05-26
12254,https://www.zameen.com/Property/islamabad_fais...,Brand New House At Most Luxurious Location On ...,House,32500000.0,8 Marla,Islamabad,"Faisal Town - F-18, Islamabad, Islamabad Capital",6 Beds,6 Baths,2178.00,14921.946740,202.342734,160618.567109,33.6844,73.0479,2024-05-26

In [28]:
isb_houses=isb_houses.dropna(subset=["price","area_sqm"])

In [40]:
# Adding .astype(str) before the extraction prevents the floating error
isb_houses["bedrooms"] = isb_houses["bedrooms"].astype(str).str.extract(r'(\d+)')
isb_houses["bedrooms"] = isb_houses["bedrooms"].astype(float)
isb_houses['bedrooms'] = isb_houses['bedrooms'].fillna(isb_houses['bedrooms'].median())

# Apply the same safety check to baths
isb_houses["baths"] = isb_houses["baths"].astype(str).str.extract(r'(\d+)')
isb_houses["baths"] = isb_houses["baths"].astype(float)
isb_houses['baths'] = isb_houses['baths'].fillna(isb_houses['baths'].median())

KeyError: 'address_B-17, Islamabad, Islamabad Capital'

In [68]:
isb_houses_encoded=pd.get_dummies(isb_houses,columns=["address"],drop_first=True)
y = isb_houses_encoded['price']
isb_houses_encoded['address_B-17, Islamabad, Islamabad Capital']

0        False
1        False
2        False
3        False
4        False
         ...
12250    False
12251    False
12252    False
12253    False
12254    False
Name: address_B-17, Islamabad, Islamabad Capital, Length: 8499, dtype: bool

In [53]:
X = isb_houses_encoded.drop([
    'price',            # The target cannot be in the training features
    'property link',    # Text URL
    'title',            # Text sentence
    'type',             # Text "House"
    'area',             # Text "5 Marla" (we are using area_sqft instead)
    'city',             # Text "Islamabad"
    'price_per_sqft',   # Data Leakage (contains price info)
    'area_sqm',         # Redundant (we already have sqft)
    'price_per_sqm',    # Data Leakage 
    'Latitude',         # Not needed for simple linear regression
    'Longitude',        # Not needed for simple linear regression
    'date_added',
     'url',
    'title',
    # Date string
], axis=1, errors='ignore')

0        False
1        False
2        False
3        False
4        False
         ...
12250    False
12251    False
12252    False
12253    False
12254    False
Name: address_B-17, Islamabad, Islamabad Capital, Length: 8499, dtype: bool

In [48]:
print("Final X Matrix Shape:", X.shape)

Final X Matrix Shape: (8499, 140)

In [57]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [59]:
model=LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [60]:
predictions=model.predict(X_test)

In [61]:
predictions

array([6.34917012e+07, 2.44087330e+08, 1.80460927e+08, ...,
       1.12409784e+08, 9.26928803e+07, 1.43409149e+07], shape=(1700,))

In [73]:
mse = mean_squared_error(y_test, predictions)
rmse = np.sqrt(mse)
mae = mean_absolute_error(y_test, predictions)

In [74]:
print("rmse",rmse)
print("mae",mae)

rmse 105440989.13236988
mae 48405047.91561417

NOW IN PRODUCTION API THE INPUT TO PREDICT IS HANDLED BY THE JSON TEMPLATE BELOW IS THE DEMOSTRATION I LEARNED

In [64]:
new_house = pd.DataFrame(0, index=[0], columns=X.columns)
new_house['bedrooms'] = 5.0
new_house['baths'] = 6.0
new_house['area_sqft'] = 5445.0
new_house['address_B-17, Islamabad, Islamabad Capital'] = 1
predicted_price = model.predict(new_house)
print(f"Predicted Price: Rs. {predicted_price[0]:,.0f}")

Predicted Price: Rs. 35,879,800