In [26]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [27]:
df=pd.read_csv("./zameen.csv")

In [28]:
df

,url,title,type,price,area,city,address,bedrooms,baths,area_sqft,price_per_sqft,area_sqm,price_per_sqm,Latitude,Longitude,date_added
0,https://www.zameen.com/Property/bahria_town_ba...,5 MARLA BRAND NEW PARK FACING HOUSE FOR SALE,House,23500000.0,5 Marla,Islamabad,"Bahria Town, Islamabad, Islamabad Capital",4 Beds,4 Baths,1361.25,17263.544540,126.464209,185823.326900,33.6844,73.0479,5/25/2024
1,https://www.zameen.com/Property/islamabad_f-7_...,Prime Location House For Sale,House,750000000.0,3.8 Kanal,Islamabad,"F-7, Islamabad, Islamabad Capital",10 Beds,0 Baths,20691.00,36247.643900,1922.255973,390166.559800,33.6844,73.0479,5/25/2024
2,https://www.zameen.com/Property/islamabad_f-7_...,Luxurious 6-Bedroom House For Sale In Prime Lo...,House,450000000.0,2 Kanal,Islamabad,"F-7, Islamabad, Islamabad Capital",6 Beds,6 Baths,10890.00,41322.314050,1011.713670,444789.878100,33.6844,73.0479,5/25/2024
3,https://www.zameen.com/Property/islamabad_f-7_...,Specious 666 Sq Yard 60x100 House For Sale In ...,House,290000000.0,1.3 Kanal,Islamabad,"F-7, Islamabad, Islamabad Capital",6 Beds,6 Baths,7078.50,40969.131880,657.613886,440988.255300,33.6844,73.0479,5/25/2024
4,https://www.zameen.com/Property/islamabad_f-8_...,Prime Location House For Sale,House,225000000.0,1 Kanal,Islamabad,"F-8, Islamabad, Islamabad Capital",5 Beds,5 Baths,5445.00,41322.314050,505.856835,444789.878100,33.6844,73.0479,5/25/2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155056,https://www.zameen.com/Property/lahore_road_sh...,5 Marla Residential Plot Is Available For Sale...,Residential Plot,2500000.0,5 Marla,Sargodha,"Lahore Road, Sargodha, Punjab",0 Beds,0 Baths,1361.25,1836.547291,126.464209,19768.439030,32.0836,72.6711,5/26/2024
155057,https://www.zameen.com/Property/sargodha_chak_...,Beautiful Laser Leveled Land Available With Hu...,Agricultural Land,15000000.0,50 Kanal,Sargodha,"Chak 74 NB, Sargodha, Punjab",0 Beds,0 Baths,272250.00,55.096419,25292.841750,593.053171,32.0836,72.6711,5/26/2024
155058,https://www.zameen.com/Property/sargodha_khush...,Agriculture Land Sale Urgent,Agricultural Land,24000000.0,48 Kanal,Sargodha,"Khushab Road, Sargodha, Punjab",0 Beds,0 Baths,261360.00,91.827365,24281.128080,988.421951,32.0836,72.6711,5/26/2024
155059,https://www.zameen.com/Property/sargodha_khush...,Agriculture Land Sale Urgent 110 Ft Front On Road,Agricultural Land,33000000.0,103 Kanal,Sargodha,"Khushab Road, Sargodha, Punjab",0 Beds,0 Baths,560835.00,58.840836,52103.254010,633.357755,32.0836,72.6711,5/26/2024
155060,https://www.zameen.com/Property/sargodha_khush...,Agriculture Land Sale Urgent Chak 74 Nb,Agricultural Land,35000000.0,83 Kanal,Sargodha,"Khushab Road, Sargodha, Punjab",0 Beds,0 Baths,451935.00,77.444765,41986.117310,833.608875,32.0836,72.6711,5/26/2024

In [29]:
isb_houses=df[(df["city"]=="Islamabad")&(df["type"]=="House")].copy()

In [30]:
isb_houses

,url,title,type,price,area,city,address,bedrooms,baths,area_sqft,price_per_sqft,area_sqm,price_per_sqm,Latitude,Longitude,date_added
0,https://www.zameen.com/Property/bahria_town_ba...,5 MARLA BRAND NEW PARK FACING HOUSE FOR SALE,House,23500000.0,5 Marla,Islamabad,"Bahria Town, Islamabad, Islamabad Capital",4 Beds,4 Baths,1361.25,17263.54454,126.464209,185823.3269,33.6844,73.0479,5/25/2024
1,https://www.zameen.com/Property/islamabad_f-7_...,Prime Location House For Sale,House,750000000.0,3.8 Kanal,Islamabad,"F-7, Islamabad, Islamabad Capital",10 Beds,0 Baths,20691.00,36247.64390,1922.255973,390166.5598,33.6844,73.0479,5/25/2024
2,https://www.zameen.com/Property/islamabad_f-7_...,Luxurious 6-Bedroom House For Sale In Prime Lo...,House,450000000.0,2 Kanal,Islamabad,"F-7, Islamabad, Islamabad Capital",6 Beds,6 Baths,10890.00,41322.31405,1011.713670,444789.8781,33.6844,73.0479,5/25/2024
3,https://www.zameen.com/Property/islamabad_f-7_...,Specious 666 Sq Yard 60x100 House For Sale In ...,House,290000000.0,1.3 Kanal,Islamabad,"F-7, Islamabad, Islamabad Capital",6 Beds,6 Baths,7078.50,40969.13188,657.613886,440988.2553,33.6844,73.0479,5/25/2024
4,https://www.zameen.com/Property/islamabad_f-8_...,Prime Location House For Sale,House,225000000.0,1 Kanal,Islamabad,"F-8, Islamabad, Islamabad Capital",5 Beds,5 Baths,5445.00,41322.31405,505.856835,444789.8781,33.6844,73.0479,5/25/2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12250,https://www.zameen.com/Property/kashmir_highwa...,House For Grabs In 8 Kanal Islamabad,House,599100000.0,8 Kanal,Islamabad,"Kashmir Highway, Islamabad, Islamabad Capital",0 Beds,0 Baths,43560.00,13753.44353,4046.854680,148040.8978,33.6844,73.0479,5/26/2024
12251,https://www.zameen.com/Property/kashmir_highwa...,"A House Of 10 Marla In Rs. 53,000,000",House,53000000.0,10 Marla,Islamabad,"Kashmir Highway, Islamabad, Islamabad Capital",0 Beds,0 Baths,2722.50,19467.40129,252.928417,209545.4537,33.6844,73.0479,5/26/2024
12252,https://www.zameen.com/Property/g_11_g-11_2_br...,Brand New House For Sale,House,55000000.0,5 Marla,Islamabad,"G-11, Islamabad, Islamabad Capital",5 Beds,5 Baths,1361.25,40404.04040,126.464209,434905.6586,33.6844,73.0479,5/26/2024
12253,https://www.zameen.com/Property/i_10_i-10_1_be...,Beautiful House At Islamabad Best Location,House,40000000.0,5 Marla,Islamabad,"I-10, Islamabad, Islamabad Capital",4 Beds,4 Baths,1361.25,29384.75666,126.464209,316295.0245,33.6844,73.0479,5/26/2024
12254,https://www.zameen.com/Property/islamabad_fais...,Brand New House At Most Luxurious Location On ...,House,32500000.0,8 Marla,Islamabad,"Faisal Town - F-18, Islamabad, Islamabad Capital",6 Beds,6 Baths,2178.00,14921.94674,202.342734,160618.5671,33.6844,73.0479,5/26/2024

In [31]:
isb_houses=isb_houses.dropna(subset=["price","area_sqm"])

In [32]:
# Adding .astype(str) before the extraction prevents the floating error
isb_houses["bedrooms"] = isb_houses["bedrooms"].astype(str).str.extract(r'(\d+)')
isb_houses["bedrooms"] = isb_houses["bedrooms"].astype(float)
isb_houses['bedrooms'] = isb_houses['bedrooms'].fillna(isb_houses['bedrooms'].median())

# Apply the same safety check to baths
isb_houses["baths"] = isb_houses["baths"].astype(str).str.extract(r'(\d+)')
isb_houses["baths"] = isb_houses["baths"].astype(float)
isb_houses['baths'] = isb_houses['baths'].fillna(isb_houses['baths'].median())

In [33]:
isb_houses.head()

,url,title,type,price,area,city,address,bedrooms,baths,area_sqft,price_per_sqft,area_sqm,price_per_sqm,Latitude,Longitude,date_added
0,https://www.zameen.com/Property/bahria_town_ba...,5 MARLA BRAND NEW PARK FACING HOUSE FOR SALE,House,23500000.0,5 Marla,Islamabad,"Bahria Town, Islamabad, Islamabad Capital",4.0,4.0,1361.25,17263.54454,126.464209,185823.3269,33.6844,73.0479,5/25/2024
1,https://www.zameen.com/Property/islamabad_f-7_...,Prime Location House For Sale,House,750000000.0,3.8 Kanal,Islamabad,"F-7, Islamabad, Islamabad Capital",10.0,0.0,20691.00,36247.64390,1922.255973,390166.5598,33.6844,73.0479,5/25/2024
2,https://www.zameen.com/Property/islamabad_f-7_...,Luxurious 6-Bedroom House For Sale In Prime Lo...,House,450000000.0,2 Kanal,Islamabad,"F-7, Islamabad, Islamabad Capital",6.0,6.0,10890.00,41322.31405,1011.713670,444789.8781,33.6844,73.0479,5/25/2024
3,https://www.zameen.com/Property/islamabad_f-7_...,Specious 666 Sq Yard 60x100 House For Sale In ...,House,290000000.0,1.3 Kanal,Islamabad,"F-7, Islamabad, Islamabad Capital",6.0,6.0,7078.50,40969.13188,657.613886,440988.2553,33.6844,73.0479,5/25/2024
4,https://www.zameen.com/Property/islamabad_f-8_...,Prime Location House For Sale,House,225000000.0,1 Kanal,Islamabad,"F-8, Islamabad, Islamabad Capital",5.0,5.0,5445.00,41322.31405,505.856835,444789.8781,33.6844,73.0479,5/25/2024

In [34]:
isb_houses_encoded=pd.get_dummies(isb_houses,columns=["address"],drop_first=True)
y = isb_houses_encoded['price']
isb_houses_encoded[(isb_houses_encoded['address_Tarnol, Islamabad, Islamabad Capital']==True)]

,url,title,type,price,area,city,bedrooms,baths,area_sqft,price_per_sqft,...,"address_Sohan Valley, Islamabad, Islamabad Capital","address_Spring Valley, Islamabad, Islamabad Capital","address_Swan Garden, Islamabad, Islamabad Capital","address_Taramrri, Islamabad, Islamabad Capital","address_Tarlai, Islamabad, Islamabad Capital","address_Tarnol, Islamabad, Islamabad Capital","address_Thanda Pani, Islamabad, Islamabad Capital","address_Top City 1, Islamabad, Islamabad Capital","address_University Town, Islamabad, Islamabad Capital","address_Zaraj Housing Scheme, Islamabad, Islamabad Capital"
1542,https://www.zameen.com/Property/tarnol_fazaia_...,Design And Constructed By Army Person10 Marla ...,House,44500000.0,10 Marla,Islamabad,6.0,6.0,2722.5,16345.270890,...,False,False,False,False,False,True,False,False,False,False
3570,https://www.zameen.com/Property/tarnol_fazaia_...,36x75 Size Double Stories House For Sale In Bl...,House,36000000.0,12 Marla,Islamabad,6.0,6.0,3267.0,11019.283750,...,False,False,False,False,False,True,False,False,False,False
3916,https://www.zameen.com/Property/tarnol_fazaia_...,Double Storey House For Sale In Block D,House,65000000.0,1.2 Kanal,Islamabad,7.0,6.0,6534.0,9947.964493,...,False,False,False,False,False,True,False,False,False,False
5683,https://www.zameen.com/Property/tarnol_fazaia_...,1 Kanal Brand New Double Unit House. Available...,House,65000000.0,1.2 Kanal,Islamabad,7.0,0.0,6534.0,9947.964493,...,False,False,False,False,False,True,False,False,False,False
7450,https://www.zameen.com/Property/tarnol_fazaia_...,1 Kanal Double Unit House Available. For Sale ...,House,65000000.0,1.2 Kanal,Islamabad,7.0,6.0,6534.0,9947.964493,...,False,False,False,False,False,True,False,False,False,False
7451,https://www.zameen.com/Property/tarnol_fazaia_...,10 Marla Brand New Double Unit House Available...,House,35000000.0,10 Marla,Islamabad,6.0,6.0,2722.5,12855.831040,...,False,False,False,False,False,True,False,False,False,False
8169,https://www.zameen.com/Property/fazaia_housing...,Block C Street 19 House 19 Near Main Dubel Roa...,House,75000000.0,1.2 Kanal,Islamabad,9.0,6.0,6534.0,11478.420570,...,False,False,False,False,False,True,False,False,False,False
8845,https://www.zameen.com/Property/fazaia_housing...,Block B Size 1 Kanal Extra Land House For Sale,House,52500000.0,1 Kanal,Islamabad,6.0,6.0,5445.0,9641.873278,...,False,False,False,False,False,True,False,False,False,False
8846,https://www.zameen.com/Property/fazaia_housing...,House number 6 Street number 3 Block D size 60...,House,65000000.0,1 Kanal,Islamabad,6.0,6.0,5445.0,11937.557390,...,False,False,False,False,False,True,False,False,False,False
9601,https://www.zameen.com/Property/tarnol_fazaia_...,Your Ideal 5400 Square Feet House Has Just Bec...,House,65000000.0,1.2 Kanal,Islamabad,6.0,6.0,6534.0,9947.964493,...,False,False,False,False,False,True,False,False,False,False
9645,https://www.zameen.com/Property/tarnol_fazaia_...,Fazaia Tarnol Triple Story Proper Corner House...,House,74000000.0,1.2 Kanal,Islamabad,9.0,6.0,6534.0,11325.374960,...,False,False,False,False,False,True,False,False,False,False
10189,https://www.zameen.com/Property/islamabad_tarn...,House For Sale Is Readily Available In Prime L...,House,9000000.0,6 Marla,Islamabad,3.0,4.0,1633.5,5509.641873,...,False,False,False,False,False,True,False,False,False,False
10565,https://www.zameen.com/Property/tarnol_fazaia_...,10 Marla Double Unit House Available. For Sale...,House,32500000.0,10 Marla,Islamabad,6.0,6.0,2722.5,11937.557390,...,False,False,False,False,False,True,False,False,False,False
11860,https://www.zameen.com/Property/tarnol_fazaia_...,1 Kanal Double Unit House Available For Sale I...,House,50000000.0,1.2 Kanal,Islamabad,6.0,6.0,6534.0,7652.280380,...,False,False,False,False,False,True,False,False,False,False
12044,https://www.zameen.com/Property/tarnol_fazaia_...,Spacious 10 Marla House Available For Sale In ...,House,30000000.0,10 Marla,Islamabad,4.0,4.0,2722.5,11019.283750,...,False,False,False,False,False,True,False,False,False,False

In [35]:
X = isb_houses_encoded.drop([
    'price',            # The target cannot be in the training features
    'property link',    # Text URL
    'title',            # Text sentence
    'type',             # Text "House"
    'area',             # Text "5 Marla" (we are using area_sqft instead)
    'city',             # Text "Islamabad"
    'price_per_sqft',   # Data Leakage (contains price info)
    'area_sqm',         # Redundant (we already have sqft)
    'price_per_sqm',    # Data Leakage 
    'Latitude',         # Not needed for simple linear regression
    'Longitude',        # Not needed for simple linear regression
    'date_added',
     'url',
    'title',
    # Date string
], axis=1, errors='ignore')

In [36]:
X

,bedrooms,baths,area_sqft,"address_Airline Avenue, Islamabad, Islamabad Capital","address_Airport Avenue Housing Society, Islamabad, Islamabad Capital","address_Airport Enclave, Islamabad, Islamabad Capital","address_Ali Pur, Islamabad, Islamabad Capital","address_Alipur Farash, Islamabad, Islamabad Capital","address_Atomic Energy Employee Society, Islamabad, Islamabad Capital","address_B-17, Islamabad, Islamabad Capital",...,"address_Sohan Valley, Islamabad, Islamabad Capital","address_Spring Valley, Islamabad, Islamabad Capital","address_Swan Garden, Islamabad, Islamabad Capital","address_Taramrri, Islamabad, Islamabad Capital","address_Tarlai, Islamabad, Islamabad Capital","address_Tarnol, Islamabad, Islamabad Capital","address_Thanda Pani, Islamabad, Islamabad Capital","address_Top City 1, Islamabad, Islamabad Capital","address_University Town, Islamabad, Islamabad Capital","address_Zaraj Housing Scheme, Islamabad, Islamabad Capital"
0,4.0,4.0,1361.25,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,10.0,0.0,20691.00,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,6.0,6.0,10890.00,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,6.0,6.0,7078.50,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,5.0,5.0,5445.00,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12250,0.0,0.0,43560.00,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12251,0.0,0.0,2722.50,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12252,5.0,5.0,1361.25,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12253,4.0,4.0,1361.25,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12254,6.0,6.0,2178.00,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [37]:
print("Final X Matrix Shape:", X.shape)

Final X Matrix Shape: (8499, 139)

In [38]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [39]:
model=LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [40]:
predictions=model.predict(X_test)

In [41]:
predictions

array([6.34917012e+07, 2.44087330e+08, 1.80460927e+08, ...,
       1.12409784e+08, 9.26928803e+07, 1.43409149e+07], shape=(1700,))

In [42]:
mse = mean_squared_error(y_test, predictions)
rmse = np.sqrt(mse)
mae = mean_absolute_error(y_test, predictions)

In [43]:
print("rmse",rmse)
print("mae",mae)

rmse 105440989.13237542
mae 48405047.91561589

NOW IN PRODUCTION API THE INPUT TO PREDICT IS HANDLED BY THE JSON TEMPLATE BELOW IS THE DEMOSTRATION I LEARNED

In [46]:
new_house = pd.DataFrame(0, index=[0], columns=X.columns)
new_house['bedrooms'] = 5.0
new_house['baths'] = 6.0
new_house['area_sqft'] = 5445.0
new_house['address_B-17, Islamabad, Islamabad Capital'] = 1
predicted_price = model.predict(new_house)
print(f"Predicted Price: Rs. {predicted_price[0]:,.10f}")

Predicted Price: Rs. 35,879,799.9648579210